### ISSUE TITLE
[Bug]: Voices - remove keychain not working

### ISSUE THREAD

**Issue by oldGreg5** [input-output-hk/catalyst-voices#2195]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Remove keychain not working.
After removing Unlock button is still there active and I can unlock account and will see all my proposals:

https://github.com/user-attachments/assets/0119815e-e013-4361-86de-1d0715f17172

### Expected Behavior

Remove keychain should work

### Project

Frontend

### What operating system are you seeing the problem on?

macOS

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```sh

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by damian-molinski** [comment]
@oldGreg5 can you retry this? I was not able to reproduce it. Possibly it was fixed in mean time

**Comment by emiride** [comment]
@oldGreg5 I just retested this and it looks like it works on deployed version

**Comment by oldGreg5** [comment]
Just checked now on dev env and problem is still there.
Steps to reproduce:
1. recover keychain 1
2. lock
3. unlock and recover keychain 2
4. remove keychain

https://github.com/user-attachments/assets/bdfe9a3f-3c84-4cb5-a492-106857104d2b
